services:
  # Workload service with image got from the API
  deployment:
    image: ${DEPLOYMENT_IMAGE}
    ports:
      - "8001:8001"

  # Publication service
  zrok:
    image: ${ZROK_IMAGE}
    depends_on:
      deployment:
        condition: service_started
    environment:
      ZROK_TOKEN: ${ZROK_TOKEN}
      UPSTREAM_NAME: ${UPSTREAM_NAME}
