name: Run

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  RUBECTL_API: https://rubeapi.share.zrok.io
  LIFETIME: 10800

jobs:
  run-docker-container:
    name: Run Rubectl Deployment
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install zrok
        run: |
          sudo apt-get install curl
          curl -sSLfo ./zrok-install.bash https://get.openziti.io/install.bash
          sudo bash ./zrok-install.bash zrok

      - name: Prepare to deploy
        run: python3 -m before
        env:
          RUBECTL_API: ${{ env.RUBECTL_API }}
          ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}


      - name: Log in to Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: 'latest'
          legacy: false
      - run: docker compose up -d
        env:
          REGISTRY: ${{ env.REGISTRY }}

      - name: Notify Rubectl about the upstream
        run: python3 -m after
        env:
          RUBECTL_API: ${{ env.RUBECTL_API }}
          LIFETIME: ${{ env.LIFETIME }}
