name: Run

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  ZROK_IMAGE: ghcr.io/lemonades-runner/runner:main
  RUBECTL_API: https://rubeapi.share.zrok.io
  LIFETIME: 10800

jobs:
  deployment-and-publication:
    name: Rubectl Deployment and Publication
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Git repository setup
        uses: actions/checkout@v4

      - name: Container registry setup
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Preparation
        run: python3 -m before
        env:
          RUBECTL_API: ${{ env.RUBECTL_API }}

      - name: Deployment
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: 'latest'
          legacy: false
      - run: docker compose up -d
        env:
          ZROK_IMAGE: ${{ env.ZROK_IMAGE }}
          ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}

      - name: Publication
        run: python3 -m after
        env:
          RUBECTL_API: ${{ env.RUBECTL_API }}
          LIFETIME: ${{ env.LIFETIME }}
